name: Release

on:
  workflow_run:
    workflows: ["build"]
    branches: [main]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    environment: cross-lerna
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build
      - name: Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          branches: |
            [
              'main',
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
